version: '3'
services:
  webapi:
    build: . # Build the web API image from the Dockerfile
    env_file:
      - .env #using environmental variable so the ConnectionString doesn't accidentally get uploaded anywhere, may use something like Azure Key Vault in the future for security
    ports:
      - "8080:8080"
    depends_on:
      - db # Ensure the database container starts first
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING} # Use an environment variable


  db:
    image: postgres # Use the official PostgreSQL image
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data # Persist database data