version: '3.8'
services:
  webapi:
    build: . # Build the web API image from the Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env # taking values from the environmental variable file I have created in root dir
    depends_on:
      - db # Ensure the database container starts first


  db:
    image: postgres # Use the official PostgreSQL image
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data # Persist database data